### ISSUE TITLE
Database backup files in GigaDB FTP server are corrupt

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1059]
The latest database backup files in the GigaDB FTP server appear to be corrupt since they are not the expected size. Therefore, they cannot be used for syncing data between the CNGB live server and the beta GigaDB website hosted on AWS Cloud.

These backup files are created on the live CNGB server hosting the GigaDB website and have the correct size. This suggests there is a problem with the transfer of the files from the live CNGB server to the FTP server.

**Comment by only1chunts** [comment]
This is a recurrent issue, and I think you are correct that its to do with the transfer rather than the generation. I was looking to get an upto date copy for my local db to play with and the most recent complete one that I could find was 2 weeks old (31 may).
We have admin rights on the live server so maybe we can put a cron job on there to push the dump file somewhere else (more stable)?

**Comment by pli888** [comment]
>We have admin rights on the live server so maybe we can put a cron job on there to push the dump file somewhere else (more stable)?

@only1chunts I've already done this. You can get hold of the database dump files from a FTP server I've set up on AWS. I will email you the access details.

**Comment by pli888** [comment]
Closing this issue because CNGB FTP server does not exist anymore. Database backup files are now available from an S3 bucket.
