### ISSUE TITLE
Create manually user account on bastion for curators

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1180]
- [x] Ensure it can manually run spreadsheet upload tool and post-upload tools

**Comment by rija** [comment]
* Created a user ``curator`` on bastion and arranged access
* limited its sudo privilege to only operate the two scripts for the  dataset upload tool workflow
* had to make changes to the tool's bash wrapper script so that:
  * it can be run by the ``curator`` user
  *  Curators can upload the spreadsheet to that user's home directory through SFTP
  * logs files are copied there after the tool has run so they don't need elevated privileges to consult them 


There's a feature branch for this which is going to be used for #1181 as well.
