### ISSUE TITLE
[S580] Create a Prometheus server on AWS

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1228]
create manually a new ec2 instance in ap-east-1, using an AMI with prometheus preloaded on it (using Debian 11 community AMI)

**Comment by pli888** [comment]
When I search the AMI Catalog for a Debian 11 with Prometheus community AMI, there is `ami-008b1fa87945c96aa` labelled: `AskforCloud-LLC-Prometheus-Debian-11`. It has a strange `Software/Hour` cost which increases the price of the EC2 instance:

<img width="1077" alt="Screenshot 2023-03-23 at 10 50 30 AM" src="https://user-images.githubusercontent.com/2101491/227088437-7f643f13-ee4e-4dbb-842a-df9dc0bb6f40.png">

Compare the above cost with the hourly, on-demand price of a `t2.medium` instance deployed in Tokyo region which is $0.0608.

Because of the increase cost, I will manually deploy a vanilla Debian 11 EC2 instance and manually install Prometheus on it.

**Comment by rija** [comment]
I believe that’s not the one I was referring to. I think there is a category of AMI  called “Community”, where you will find open source images for OSes and popular tools that are not metered.

**Comment by pli888** [comment]
When I click on `Community AMIs` tab and search for AMIs using `prometheus` keyword and filter for Debian OS then I see the following AMIs listed:

<img width="1712" alt="Screenshot 2023-03-23 at 6 14 20 PM" src="https://user-images.githubusercontent.com/2101491/227173205-da286ef0-9f79-43d0-ba66-2f4b5ef2e8ab.png">

I'm not able to see an AMI containing prometheus that does not have added on support surcharges.

**Comment by pli888** [comment]
Closing this issue as there is documentation created for how to install Prometheus on a Debian 11 EC2 instance [here](https://github.com/pli888/gigadb-website/blob/ec2-prometheus-server/docs/awsdocs/INSTALL_PROMETHEUS.md).
