### ISSUE TITLE
[S1136] Troubleshoot current spreadsheet upload issue

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1230]
Load spreadsheet known to be accepted
Get rid of all logging
Look at the current failing spreadsheet, identify the problem, and add detailed (with context) logging about the issue and inform the curators what that logging looks like

**Comment by only1chunts** [comment]
Some interesting things I have discovered by attempting to load spreadsheets with KNOWN errors:
If there is a structural issue in the excel spreadhseet e.g. too many commas in the funding field, or extra rows where there shouldn't be, or missing values that must be present, then the java.log file includes the line 

`fillTable output: false`

But with no indications as to where the problem lies.

However, if the structure of the input file is OK it gives fillTable output: true and proceeds to the validation step.

If the values in the Excel spreadsheet are causing a problem, e.g. a dataset_type value that is not present in the list of allowable values then the java.log file includes this line:

`validation output: false`

In addition, there are other pointers within the error log that suggest the cause of the failure, in the case of the unknown dataset type (Genomics instead of Genomic) it shows this text in the java.log file :

`contentXXX: Genomics
target: dataset_type
content: Genomics
values: [Genomic, Metagenomic, Epigenomic, Proteomic, Transcriptomic, Metabolomic, Neuoscience, Bioinformatics, Workflow, Software, Imaging, Network-Analysis, Genome-Mapping, ElectroEncephaloGraphy(EEG), Metadata, Metabarcoding, Virtual-Machine, Climate, Ecology, Lipidomic, Phenotyping]`

**Comment by rija** [comment]
@pli888 you may be interested in this ticket. 
I never got to do what it says, but it may be worth considering it, plus @only1chunts observations above,  which I didn't notice until now.

**Comment by pli888** [comment]
Work on practising excel spreadsheet upload is now reported on this [Google doc](https://docs.google.com/document/d/12BAmRpqy19hrqaCNN8FTGhx9B2paPkzRO_KoLPAXPOI/edit).
