### ISSUE TITLE
dataset admin page has issues with thumbnail image updates

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1325]
**Describe the bug**
I uploaded a dataset using the upload script in the beta server, that worked fine.
Then in beta.gigadb.org i found the dataset I'd just uploaded, tick. as expected there was no thumbnail image since the upload script doesn't do that, so I tried to add the one I wanted, this is when things started to go wrong!
First I attempted to simply "add" the image file by clicking the button and selecting the relevant file, clicked save ... no new image appeared in the dataset mockup :-(
I went back to the dataset-admin page, tried to click the "delete thumbnail" button, it asked if I was sure, so I clicked yes. I then tried to upload the image again, but then it all went pair shaped! Nothing now works for that dataset :-( I cant even see the dataset admin page for it anymore! The screenshot below shows what the dataset-admin page shows now.
Of note, when I said "yes I want to delete the current thumbnail and metadata" nothing appeared to change on the screen, i.e. the metadata fields for source, license etc all still had the values in them, despite the warning telling me they would be immediately deleted. My Guess is that the information was deleted from the database, but nothing told the web-interface so when I clicked save the database was missing vital data-points that had been deleted! (maybe?!)

![image](https://github.com/gigascience/gigadb-website/assets/6037145/22860cc8-c312-473e-8941-a04644862b81)

**Comment by tuli** [comment]
FYI: I have just successfully added a thumbnail image using the same method Chris did ("choose file") for 102420 https://beta.gigadb.org/dataset/102420/token/ekYcTgAR7zlbSN6z so it's not an issue for all datasets.

**Comment by rija** [comment]
the DOI Chris tried to use is `102422`

**Comment by rija** [comment]
Hi @only1chunts 
I haven't been able to reproduce this issue.

1) From the dataset form, I've uploaded a thumbnail to that dataset `102422` on my AWS environment and after saving the form, the thumbnail appears on the mockup view.
2) Then I proceeded to delete only the image by clicking the [x] button, and after saving the form, and navigating to the mockup view, the generic thumbnail appears on the mockup view but with the image metadata as expected.
3) then proceeded to delete both the image and the metadata by clicking the red button to remove image+metadata, 
and after saving the form, and navigating to the mockup view, I saw the generic image and generic metadata
4) I've also tried additional scenario where I re-uploaded an image after 3) to see the new image and new metadata to appear on the mockup view.
5)  and I run the above cycle again

So, it all works as expected on this dataset (I've also tried on another dataset).

The only thing to bear in mind: 

After clicking the red button to delete both image and metadata, it takes a non-zero time for the action to complete (because it actually moves the image into a "bin" on Wasabi), and during that time you should not do anything. When it's done (after a few seconds), the generic image will appear on the form, signalling the old record and image was successfully deleted . Then you can save the form and go to the mockup view to see the changes.  
There is no visual indication that something is happening during that time, and we should probably do something about this (i.e: spinner), but that kind of issue and fix probably make this not a high impact level of bug anymore.
