### ISSUE TITLE
Ensure the active bootstrap dependency is from CDN only

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1356]
* Remove legacy Bootstrap LESS local installation
* Make sure all the LESS files that were dependent on it have been refactored inside the `less/current` structure
(it should be the case but need double checking)
* Remove the legacy  site-specific LESS files 

The project has automated acceptance tests.
After this work is done it is expected that they are still passing.

**Comment by luistoptal** [comment]
The local bootstrap powers the styles of most if not all admin pages. This is because these pages use a different layout than the rest of the site, and this layout loads the site.less file that imports local bootstrap

One straightfoward solution is to load the same bootstrap version from a cdn so that most styles stay intact, and then add a few supplementary styles for anything that still breaks

This would probably be provisional until the admin styles are revamped to the newer look, and then we could switch to the newer layout which uses a newer bootstrap version

**Comment by rija** [comment]
this work is done
