### ISSUE TITLE
Update the admin section with legacy styling to use the newer styling

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1358]
The admin part of the gigadb.org use old legacy styling.
* It needs to be updated to match the style of the public part of the web site
* the call to actions buttons on the lists need to be upgraded to match the public site style

We do not expect additional tests scenarios to be added to the existing PHP-based test suite but the existing ones should still be passing.
We do expect thorough manual testing however.
Also, if you are familiar with UI test tools like Playwright or Cypress, feel free to use them.

**Comment by luistoptal** [comment]
- [ ] #1460

**Comment by rija** [comment]
Hi @only1chunts,
There are some endpoints on GigaDB we have forgotten about and are seemingly not linked from anywhere.
Do we need them?
Example: https://staging.gigadb.org/adminDatasetSample/

The pattern here is to take the URL of an admin page for specific object and remove the /admin/ part and the result will just show a list of these objects (dataset samples in the case of the example above) with associated properties

If we don't need them, it will save Luis time from overhauling them, and I can also remove all the code responsible for their generation (less code is always better, especially the untested kind like those)

**Comment by rija** [comment]
Hi @only1chunts, @pli888,

There's a report at this page:

https://staging.gigadb.org/report/index

We suspect it's supposed to show a graph based on the selected date range and DOI selection in the form below.
It's currently broken on staging.gigadb.org

Is it something we use on CNGB gigadb.org ?
Is it working on CNGB gigadb.org?
Do we we know what powers the graph creation? 
How important is it for it to be working on the future live gigadb.org?

(I'm starting to suspect there's a script on the CNGB server used for this and that script is not existent on AWS deployments hence the broken symptom on staging.gigadb.org)

**Comment by only1chunts** [comment]
This answer was in reply to the question

> https://staging.gigadb.org/report/index
> 
> We suspect it's supposed to show a graph based on the selected date range and DOI selection in the form below.
> It's currently broken on staging.gigadb.org
> 
> Is it something we use on CNGB gigadb.org ?
> Is it working on CNGB gigadb.org?
> Do we we know what powers the graph creation?
> How important is it for it to be working on the future live gigadb.org?
> 
> (I'm starting to suspect there's a script on the CNGB server used for this and that script is not existent on AWS deployments hence the broken symptom on staging.gigadb.org)
> 
> 

You are correct with what its meant to show, it is based on the Google analytics, so it stopped working when they pulled the plug on that well over a year ago. I suspect there are better ways to visualise dataset usage, and we have an epic about doing that work somewhere... #137 , #161 , #942
We can remove the current content of this page and replace with some place-holder text like "under-development" or something.

**Comment by only1chunts** [comment]
> There are some endpoints on GigaDB we have forgotten about and are seemingly not linked from anywhere. Do we need them? Example: https://staging.gigadb.org/adminDatasetSample/
> 
> The pattern here is to take the URL of an admin page for specific object and remove the /admin/ part and the result will just show a list of these objects (dataset samples in the case of the example above) with associated properties
> 
> If we don't need them, it will save Luis time from overhauling them, and I can also remove all the code responsible for their generation (less code is always better, especially the untested kind like those)

I have no idea why the display of https://staging.gigadb.org/adminDatasetSample/ looks like it does? The page we use is called https://staging.gigadb.org/adminDatasetSample/admin and it has more information and a tabular layout. So I dont care what happens with the former as long as the later is still present and functional!

**Comment by luistoptal** [comment]
@rija @only1chunts 

This is a list of outstanding **accessibility** issues in the **admin pages**. Minor and low hanging a11y issues were fixed, but these are a bit more involved / less trivial. Since the task for admin pages was to just update the style and not explicitly make them fully accessible, I'll await for confirmation

* PAGE: http://gigadb.gigasciencejournal.com:9170/adminDataset/admin

![image](https://github.com/gigascience/gigadb-website/assets/143437854/08a670a2-e9ac-42f3-b338-2351d4770e48)

  * Header has filters and sorting, but it is not very obvious visually
    * Sorting cells: add carets. Highlight entire cell on focus. Ideally links would be buttons, or have role button. Use `aria-sort` attribute
    * Filter inputs: add labels for screen readers to filter inputs
  * When filtering or sorting is used, keyboard focus is lost (because there is a page reload), keep keyboard focus to the last focused element

--> The above issues related to filtering and sorting apply to any page that has such tables, and most likely a fix could be implemented on a reusable component

![image](https://github.com/gigascience/gigadb-website/assets/143437854/e2db9164-4316-4dbf-b705-ec6e1e0f127e)

* This is more a UI issue but some cells show unparsed html elements. I am assuming this comes directly from the DB. It is probably not safe to parse this as html directly, for security reasons. Is this an issue in production, or can this be ignored?

* PAGE: http://gigadb.gigasciencejournal.com:9170/adminAuthor/admin

![image](https://github.com/gigascience/gigadb-website/assets/143437854/c9355980-b513-4739-88ad-c5ad9366f126)

* there is a modal in this page that can be seen when trying to merge an author. This modal does not trap focus (underlying elements can still be focused). This is not good for keyboard navigation users as modals should act as focus traps

* PAGES http://gigadb.gigasciencejournal.com:9170/adminDataset/create // http://gigadb.gigasciencejournal.com:9170/adminDataset/update/id/5

![image](https://github.com/gigascience/gigadb-website/assets/143437854/51c3a909-ecd8-4797-8c0e-9b2465bcaa20)

  * Date dropdown is unusable via keyboard (but user could still type the date manually as in a regular text input). This is a third party library (Jquery-ui) and it is possible that it is very outdated or not built with accessibility in mind

**Comment by only1chunts** [comment]
Thanks @luistoptal 
 - Table sorting - this is something we have tickets for already #1163 & #1155, and it would be nice to have them done sometime.
 - HTML elements in the database are sometimes required to aid display in the public dataset pages, but there should be a better way to do this. e.g. that species name you highlighted should be displayed in italics hence the <em> html tag around it to make it display in the public dataset page as italics.
 - Focus query - outside my expertise, but happy to go with whatever the "norms" are for such things.
 - date boxes, again if its adding more functionality to aid accessibility then we should look into it.

**Comment by rija** [comment]
work done
