### ISSUE TITLE
7. Rehearse DB backup restoration and make sure there are no errors doing so, and that we can continue provisioning the environment afterwards

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1418]
a. Must be easily restorable
		b. Must still be able to provision the environment after that
    c. Restore up to 1 h before incident (point in time method)
    d. Potentially get rid of problematic methods of restoration

**Comment by pli888** [comment]
On Tue 19 Dec 23, I was able to restore RDS instance for beta.gigadb.org using:

- [x] Database backup file stored in S3.
- [x] RDS database snapshot.

Point in time restoration using AWS automated database backup was not possible due to an internal AWS console problem. The AWS automated database backup was back available for use in AWS console for beta.gigadb.org on Wed 20 Dec 23 but this was not tested because dataset ftp_site and file location URLs had already been updated to Wasabi links in database.
