### ISSUE TITLE
1. Identify peculiar datasets (which include the ones that are held up by BGI/CNGB legalities)

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1422]

**Comment by pli888** [comment]
Using the Large GigaDB datasets [spreadsheet](https://docs.google.com/spreadsheets/d/13DVSESKMTewlv11Z7cVNPEBMo4lzQa4X_dB0OFc5N_Y/edit#gid=0), there is now a new column named `Exclude from file location update`. Any datasets labelled `Yes` in this column should not have their File location URLs automatically updated using the files metadata console tool for the (peculiar) reasons given in the cell comment. There are 2 reasons:

1. The dataset has too many files for the files metadata console tool to process which will result in a memory problem.
2. The dataset has not been transferred from CNGB to Wasabi.

Datasets not listed in this spreadsheet are assumed to have been transferred to Wasabi.

The [spreadsheet](https://docs.google.com/spreadsheets/d/13DVSESKMTewlv11Z7cVNPEBMo4lzQa4X_dB0OFc5N_Y/edit#gid=0) will be updated as and when datasets are copied over to Wasabi but for now I think we can close this ticket since this work to identify peculiar datasets has been addressed.
