### ISSUE TITLE
set release date to complete the citation details of the dataset

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1530]
**Describe the bug**
This may be related to #963 & #1528 

When I set the release date on a private dataset it is not displayed in the dataset mockup view and the citation information does not show the year as it should

**To Reproduce**
1. Go to https://beta.gigadb.org/adminDataset/update/id/2713
2. Set the release date to any date
3. Click on 'save'
4. view the mockup page
5. See error- no release date shown and no year in the citation information

**Expected behavior**
Setting a release date should show in the mockup page

**Screenshots**
I have entered a publication date:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/fcfb941b-5e58-4759-9578-fbb2704d4fa0)

But no year has appeared in the citation part:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/0704e9be-52bd-49b5-ac85-6b2f80b35a88)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kencho51** [comment]
Hi, 

After investigation, the reason of release date on a private dataset  not showing in beta is because `caching` is turned on for mockup page, so the updated release date cannot be seen even after save.

This problem will be fixed after https://github.com/gigascience/gigadb-website/pull/1560 has been reviewed and merged.
