### ISSUE TITLE
Dataset Types - populate Description

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1658]
**Is your feature request related to a problem? Please describe.**
We have 24 Dataset Types: http://gigadb.org/adminDatasetType/admin
12 of them do not have a Description.

**Describe the solution you'd like**
Add a Description.  We have 4 curators so could do 3 each. 

**Describe alternatives you've considered**
Doing nothing and sighing deeply when I want to check on a Definition and find there isn't one. 

**Additional context**
We should identify if there is an approved source/ontology that we can use and if not, agree on standards.

**Comment by only1chunts** [comment]
I agree in principle, but I've been putting it off because we need to update the list of dataset types to match the SRAO slim (already used in GigaByte), all of which have community-written descriptions.  see doc [here](https://docs.google.com/spreadsheets/d/1shH-QK-UT9HD88ysWFHVq5xUenxAmcbg/edit#gid=127246064) as well as Epic #712.
If you wish to add your own descriptions now via admin pages if it will be of use thats fine, but its only us 4 curators that can see them at present anyway!
I will close this ticket as not required as its coverd by epic 712.
