### ISSUE TITLE
Inconsistent buttons on dataset admin page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1767]
**Describe the bug**

**To Reproduce**
1. Go to any dataset admin page, e.g. https://staging.gigadb.org/adminDataset/update/id/2748
2. Scroll down to bottom
4. See buttons at bottom un-aligned and with odd formatting (see screenshot):
**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/6037145/db9fb482-3aea-49b1-ba77-bbc810b842ac)

**Expected behavior**
The buttons should be central and uniform in design.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome 
 - Version : 122.0.6261.129 

**Additional context**
There are similar issues on live that we have lived for a very long time, so this is not a blocker!

**Comment by rija** [comment]
and set of buttons is preferred to be on the middle on the screen like in other pages

**Comment by rija** [comment]
Hi @luistoptal,

maybe something for you to look into?

**Comment by luistoptal** [comment]
like this?
![image](https://github.com/gigascience/gigadb-website/assets/143437854/47d193bf-20d5-4e0d-ac77-e65209dbd579)
I reordered the buttons as I felt otherwise it's strange visually. The first two buttons are related, but unrelated to the other two (back and confirm actions, respectively)

The above layout feels a bit uneven so I also created a few variations:

With separator:
![image](https://github.com/gigascience/gigadb-website/assets/143437854/7c3b5c4f-7d77-45b1-b832-2435b45af27c)

Buttons have same width / not full width:
![image](https://github.com/gigascience/gigadb-website/assets/143437854/8e9a2141-50e0-4ec9-86b9-56311c856893)

**Comment by only1chunts** [comment]
Thanks Luis, they all look fine. My personal preference would be the last one shown above "Buttons have same width / not full width:"

As a note, the Open Private URL is more related to the right two than the left one, and it is actually likely to be the most used button, so perhaps should be the right hand most one? but we'll get used to whatever order they are in :-D
