### ISSUE TITLE
New Version Alert pop up  

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1825]
**Describe the bug**
If you view a dataset which has a newer version  you get a pop up alerting you. If you choose 'Continue to view old version' the box should vanish, but it doesn't, it persists. Only if you choose 'close' does it vanish. 

**To Reproduce**
1. Go to https://gigadb.org/dataset/100209
2. Click on 'Continue to view old version'

**Expected behavior**
If I click "Continue to view old version" I would expect the box the vanish. 

**Screenshots**
![Screenshot 2024-04-23 at 11 00 15](https://github.com/gigascience/gigadb-website/assets/1359170/59997498-9d79-44cf-af66-0e3ba22eacdd)

**Desktop (please complete the following information):**
 - OS: Ventura 13.4
 - Browser- Safari 
 - Version 16.5 

**Additional context**
It's easily solved by clicking 'close' so it's just a little bug.

**Comment by only1chunts** [comment]
Good spot! I agree with your expected action.
Also its probably not worth having a "close" option, the only two choices should be "Continue to view old version" or "View new version", either click would resolve the pop-up in some way.

**Comment by rija** [comment]
Hi @luistoptal,
Could you add this issue to your Todo list?

**Comment by luistoptal** [comment]
@rija this is the part of the view that renders the buttons of the popup:

```
      <div class="modal-footer">
        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
        <a href="/dataset/<?= $relation['related_doi'] ?>" class="btn btn-default">View new version</a>
        <a href="/dataset/<?= $relation['dataset_doi'] ?>" class="btn btn-default">Continue to view old version</a>
      </div>
```

As you can see the `Continue to view old version` merely reloads the page, so the alert pops up again.

One way to fix is to simply update the `Continue to view old version` to close the popup. This would still be a bit annoying because anything that reloads the page (for example the samples and files pagination) would should the popup again

A possibility would be to store in the browser a dataset key and a timestamp or expiration date when the user clicks on the `Continue to view old version` and on page reload access the client memory and detect the value to avoid rendering the popup if necessary

Does it sound like a good approach?

**Comment by only1chunts** [comment]
I think having the "Continue to view old version" button can just close the pop-up. I dont mind annoying people that persist in looking at an older version when there is a new version they should probably use instead :-)
When we set it up originally I did toy with idea of just re-directly without the pop-up, but there are perhaps some legitimate reasons for viewing the older version so we'll keep it as a possibility. Thanks.

**Comment by only1chunts** [comment]
The button now behaves as expected, thank you. Although it is still showing 3 buttons instead of the expected 2, i.e. there is no need for button saying "Close" when that action is performed by selecting the "Continue to browse old version" button.

**Comment by rija** [comment]
All aspects of this issue are now fixed, so closing
