### ISSUE TITLE
If there is a good one, install a xls2csv on bastion too

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1889]

**Comment by rija** [comment]
Open-source, trustworthy, still maintained  tool that can be integrated in our workflow for this are hard to come by.
The most promising projects I found are below:

* https://github.com/libxls/libxls
* https://github.com/python-excel/xlrd

But both are libraries so they require development (and not in PHP) to be useful to us.
Because of that , in the current context, I'm closing this ticket as in it is not necessary to complete the user story
If we think we want to follow that route, we can create at top-level user story specifically for this work.
