### ISSUE TITLE
Web pages used in new user onboarding workflow still use the old design

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1892]
**Describe the bug**

web pages used in new user onboarding workflow still use the old design

**To Reproduce**

After spinning up your local environment:

* Go to http://gigadb.gigasciencejournal.com/user/confirm/401
* Go to http://gigadb.gigasciencejournal.com/user/welcome/id/401

**Expected behavior**

the page should have the new design

**Additional context**

this issue is a spin-off of #1818

**Comment by luistoptal** [comment]
Part of this issue comes from the fact that the old layouts are the defaults and the newer layouts were explicited page by page (before each render call)

I think it might be a good time to consider the following in a refactoring / technical dev ticket:

- Delete old layout files and remove the `new_` from the name of the new layouts
- Set new layout as the default
- Either update or delete the `column1` and `column2` files (and the `new_` ones) after confirming whether they serve a purpose or not
- Update the instances of `public $layout =`
- Remove setting layout that happens before each render call, except when it's explicitly necessary
- consider removing layout duplication (for example do we actually need a new_main and a new_faq layouts when most of it it's the same code? Is there a better way to handle whatever small differences are there?)

The only shortcoming is that any pages whose layouts have not been updated (if any) might look a bit funky (mostly lack of proper spacing) but I think that is preferable to showing a completely different appearance

Main benefit is to reduce technical debt and remove unused files

@rija @only1chunts is this something we want to spend time with?

**Comment by rija** [comment]
Hi @luistoptal,

The suggestion is very much in line with what I want to see happening as that old frontend architecture will keep causing frictions, confusions and inefficiencies whenever we need to do something on the frontend.
And, I the redesign work stream won't be complete unless the old frontend architecture is fully removed.

However, there is a problem in that the old frontend architecture seems to be very much used in the Submission Wizard codebase, and the team's current focus in not on that subsystem (we are finalising migration/switchover, then its going to be File Upload Wizard, and only then Submission Wizard), so you will not have backend support (which is necessary given its current state)  if you were to redo the frontend architecture of Submission Wizard now.

So, the seemingly wisest path would be for you to continue selectively update old pages to new styles as we uncover them like the brief of this ticket ; and then do the removal of the old frontend architecture as part of the team's focus on Submission Wizard work in the next couple of milestones. 

One thing I'm pretty certain of, is that once the File Upload Wizard and Submission Wizard have been redeveloped, there is no reason at all to keep any of that old frontend crufts, and we can go and safely clean it out.

And there is an alternative approach: you going ahead with the removal of the old frontend architecture now, knowing it is likely to break Submission Wizard UX, but the benefit is that once done, any UX work from then on will be more efficient (UX bug fixes and enhancement to the website, File Upload Wizard work).

The Submission Wizard is currently decommissioned anyway, and I believe it will need a redesign as the vision for it has evolved. So that when the team get to focus on Submission Wizard, we can rebuild it completely front and back.

**Comment by only1chunts** [comment]
@rija, given the submission wizard work was done by an external team (White Label) quite a few years ago and has never been properly integrated or used I think your alternative suggestion of basically rebuilding it front and back is going to be the way forwards.

**Comment by luistoptal** [comment]
@rija @only1chunts If I understand correctly, then the conculsion is that I can now start with all the tasks I mentioned in my last comment, and let the submission wizard break in terms of UX because it will be rebuilt anyway

**Comment by rija** [comment]
@luistoptal  Yes please!

**Comment by rija** [comment]
@luistoptal 

>consider removing layout duplication (for example do we actually need a new_main and a new_faq layouts when most of it it's the same code? Is there a better way to handle whatever small differences are there?)

The layout is supposed to hold the part common to all views, so we should have only one and  the difference should probably be moved to the views files.
If multiple views need to share the bits that was previously on a specific  layout, those bits should be moved to partials to be included in the views needing them.

**Comment by luistoptal** [comment]
@rija I see a bunch of files under docs/apidocs that reference some layouts that will be removed (e.g. column1)

Are these docs in use somewhere? Should they be updated?

Same for files *.php.txt

That seems like a lot to maintain so want to crosscheck

**Comment by luistoptal** [comment]
@rija I think this issue can be closed as once the layouts are refactored all pages will use the new design and the PR is already created

**Comment by luistoptal** [comment]
the pages mentioned in this ticket needed a revamp. #2083 fixes it
