### ISSUE TITLE
5) Add curators manual for operating the tool

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1968]

**Comment by pli888** [comment]
From working on this task in my [feature branch](https://github.com/pli888/gigadb-website/tree/curator-manual), I found a couple of issues:

Executing `calculateChecksumSizes` as a curator user on bastion is currently broken:
```
[peterl@ip-10-99-0-142 user888]$ sudo /usr/local/bin/calculateChecksumSizes 100888
Created 100888.md5
Created 100888.filesizes
2024/07/27 05:39:21 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
2024/07/27 05:39:21 Failed to create file system for "aws_metadata:gigadb-datasets-metadata": didn't find section in config file
```

Since `calculateChecksumSizes` is called using sudo, it will look for /root/.config/rclone/rclone.conf that is not created. There is a `~/.config/rclone/rclone.conf` created each curator user's home directory and it is this config file that should be used in `calculateChecksumSizes` when copying doi.md5 and doi.filesizes files into S3 bucket. Actually, we can stop copying these files to S3 bucket and have `fileMetaToDb` use the files in the dropbox directory.

When executing `sudo /usr/local/bin/postUpload 100142`, it fails to update file sizes in the dataset:
```
* About to update files' size for 100142
Number of changes: 0
```

It is strange that the `Number of changes: 0` for `About to update files' size for 100142`. I suspect there is a mismatch between the delimiter used to separate file size values and file names in doi.filesizes, and the delimiter used to parse these lines in the file size update tool.

**Comment by pli888** [comment]
From resolving the problem with updating md5 values for dataset 102555, it would be useful if the md5 update tool displays a useful error message when it is unable to find a file listed in doi.md5 to update in the database. It should also continue updating md5 values for files and not break from loop if it is unable to find a file in the database.
