### ISSUE TITLE
It takes a long time to delete a file

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#2042]
**Describe the bug**

**To Reproduce**
1. Go to https://gigadb.org/adminFile/admin
2. Click on the delete icon for a file
3. See a spinning wheel
4. Wait a long time for the file row to disappear and for the spinning wheel to stop

**Expected behavior**
The file entry should be removed promptly

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
this behaviour seem to have appeared with the merge of PR #2017 that fixes #2015.

my intuition tells me it's related to Postgresql indexes and the database transaction that wraps the deletion of the associated entries from the file_attributes table and then of the row in the file table.

**Comment by alli83** [comment]
@rija it's something I noticed while fixing the problem. there is definitely some code that needs to be reworked. On the ticket, no substantial changes on the code. Given that a new ticket should be assigned, I didn't fix it in this #2017

**Comment by alli83** [comment]
@rija it's something I noticed while fixing the problem. there is definitely some code that needs to be reworked. On this ticket, no substantial changes on the old code. Given that a new ticket should be assigned, I didn't fix it in this #2017 PR.
the different for loop should be avoided because a a delete is triggered for each relation atm (n+1). 

I have another PR with deleteAll executing a single SQL delete instead of the foreach.

**Comment by rija** [comment]
Fixed in PR #2043
