### ISSUE TITLE
Using an elastic IP address on the AWS instance hosting GigaDB staging server

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#284]
Hi @rija,

A staging server for GigaDB can be hosted using an AWS EC2 instance. This AWS EC2 instance is allocated with a new IP address when it is deployed. If a new EC2 instance for staging GigaDB is created then it gets a new IP address which then means this new IP address has to be re-mapped to the domain name of the staging server.

An AWS EC2 instance could, if provided during its creation using Terraform, be allocated with a static, elastic IP address which has already been mapped to the staging server domain name.

**Comment by rija** [comment]
Hi @pli888 ,

That's a good point.

Although it's also possible (and in theory, better approach) to consider the link IP<->Domain ephemeral  and therefore eligible to be recreated whenever provisioning a new instance (and Terraform has suitable providers for major DNS services), it may not desirable here because:
* The Ansible scripts are setup to expect IP addresses and woud need rethinking if using domain in host inventory
* The domain you want to use for staging is probably attached to gigascience whose DNS server  could be hard to interact programmatically with.

In which case, your suggestion is appropriate and could be implemented by adding something like the below code to the TF script (assuming an Elastic IP is created in AWS console beforehand and tagged with "EIPForGigaDBStaging")

```
data "aws_eip" "staging_eip" {
  tags = {
    Name = "EIPForGigaDBStaging"
  }
}

resource "aws_eip_association" "eip_assoc" {
  instance_id   = "${aws_instance.staging_dockerhost.id}"
  allocation_id = "${aws_eip.staging_eip.id}"
}
```

Let me know if that works for you

**Comment by pli888** [comment]
It works with the code below:
```
data "aws_eip" "staging_eip" {
  filter {
    name   = "tag:Name"
    values = ["EIPForGigaDBStaging"]
  }
}

resource "aws_eip_association" "staging_eip" {
  instance_id   = "${aws_instance.staging_dockerhost.id}"
  allocation_id = "${data.aws_eip.staging_eip.id}"
}
```

If there is no elastic IP with the tag Name = EIPForGigaDBStaging then it will return an error message:
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_eip.staging_eip: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.aws_eip.staging_eip: 1 error(s) occurred:

* data.aws_eip.staging_eip: data.aws_eip.staging_eip: no matching Elastic IP found
```

I could try to write a conditional to check for the presence of the elastic IP but not sure if this is necessary.

**Comment by rija** [comment]
In the cloud, given the potentially large numbers of resources and environments used, I find it useful to tag everything.
Given that,  as part of deploying a new instance, you have to manually associate the EIP with the GigaDB staging domain name anyway, adding a tag is part of that. The instanciation of an EIP is hopefully a one-off task.

The TF error itself can be a reminder that that manual step needs to be done as a pre-requisite.
so to me, it doesn't seem like there's a lot of value in checking.
