### ISSUE TITLE
Update CSS in admin pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#289]
I just had a quick look at that URL, its quick! much quicker than the production version :-D 
The only issue I spotted was that all the admin pages are missing any formatting, i guess its the CSS of the old version of the website that was still be used in the admin pages thats gone? can the admin pages use the new version CSS?
NB the wizard is also effected because that currently uses the old style sheet too

_Originally posted by @only1chunts in https://github.com/gigascience/gigadb-website/pull/287#issuecomment-472791510_

**Comment by only1chunts** [comment]
additionally : 
- the "Dimensions" link is missing (meant to be next to the google scholar and euroPMC links)
- the Guidelines page links are missing from the Help dropdown menu
There are other things that need fixing in the github version that have been done directly in the production version over the last few months, these are listed in the ticket #293

**Comment by jessesiu** [comment]
@only1chunts I checked the code on the website. For the local deployment, the site.css file is in the css directory. But it missed in my AWS deployment, not sure what happens. The site.css file is in the .gitignore list, it needs to get generated from the site.less file when building the website. @pli888 can you check whether it happens is your AWS deployment.

**Comment by pli888** [comment]
> For the local deployment, the site.css file is in the css directory.

@jessesiu The local deployment of GigaDB seems to be using the old way of rendering Admin pages in [SiteController.php](https://github.com/gigascience/gigadb-website/blob/develop/protected/controllers/SiteController.php). Specifically, look at the `actionAdmin()` function and compare this with `actionIndex()` which uses the latest web layout. To fix this, the `actionAdmin()` function needs to be updated.

**Comment by pli888** [comment]
Applying the the latest GigaDB [common.css](https://github.com/gigascience/gigadb-website/blob/develop/css/common.css) on admin pages can cause errors relating to jQuery. For example, if you go to  `/adminDataset/update/id/$dataset_id`:

<img width="680" alt="error_jquery" src="https://user-images.githubusercontent.com/2101491/67255651-b8e84b00-f4b5-11e9-9c38-6efa4cacace2.png">

This is caused by the 2.2.4 version of jQuery being used in the HTML head section which is generated by `new_main.php` in the `protected/views/layouts` directory. If jQuery-1.9.1 is used then these errors disappear.

**Comment by pli888** [comment]
>The only issue I spotted was that all the admin pages are missing any formatting, i guess its the CSS of the old version of the website that was still be used in the admin pages thats gone? can the admin pages use the new version CSS?
NB the wizard is also effected because that currently uses the old style sheet too

Admin pages are being displayed now with correct layout - see [staging server](https://gigadb-staging.gigatools.net/site/admin). Seems like the staging server needs to be deployed with `deploy_app` step in Gitlab CI/CD to get this working.
