### ISSUE TITLE
Add docker image volume in staging server 

### ISSUE THREAD

**Issue by jessesiu** [gigascience/gigadb-website#342]
The create new user page cannot display the CAPTCHA image to check that a person and not a robot is creating a new user account. It seems that the create new dataset page is not able to upload the CAPTCHA image into the `images` directory.

1. Go to http://gigadb-staging-jesse.gigatools.net/user/create
2. Can't see the verify code
-------
1. Go to http://gigadb-staging-jesse.gigatools.net/datasetSubmission/create1
2. Upload the test image and finished the submission process
3. The test image can't display on the dataset page

@rija The production version has application and web container. These two containers both have the image directory mounted inside them. Can we set the unique image volume to store all images then mount to the containers?

**Comment by rija** [comment]
Hi @jessesiu,

Yes, you are right. You can mount the "images" directory into both containers, and that should fix the issues you are seeing. It's already mounted in the application container. For the web container, you can add the snippet below in ``ops/deployment/docker-compose.yml`` under the **web: > volumes:** section:
```
- ${APPLICATION}/images:/var/www/images
```
**Note:** You don't want to mount the entire project directory in the web container for security reasons.

You also need to remove the instruction below from ``ops/packaging/Web-Dockerfile``:
```
COPY images /var/www/images
```

**Comment by jessesiu** [comment]
Hi @rija 

Thanks, I tried your method to add volume in docker-compose.yml file yesterday. It works in the local deployment. But it failed for the staging deployment. 

[http://gigadb-staging-jesse.gigatools.net/user/create](http://gigadb-staging-jesse.gigatools.net/user/create)

Do you think the images volume also needs to be added in docker-compose.staging.yml or any other deployment config files?

**Comment by rija** [comment]
Hi @jessesiu,

staging and production containers are different because they have to be immutable, so the project root (including the images directory) is backed in the container image. That's why you don't see them mounted on the "web" or "application" service in the staging docker-compose file.

Only directories use for programmatically generated content, the "assets" directry is mounted and shared between both.

The issues on staging is that the "images/tempcaptcha" directory should be treated the same way (as "assets") and it's not.

Therefore, in the staging docker-compose file, we should add under "web: > volumes:", and "application: > volumes:" the volume mount below:

```
- captchas:/var/www/images/tempcaptcha
```

and under the "volumes:" section at the end of the file, add the following volume:

```
	captchas:
```

**Comment by pli888** [comment]
> Therefore, in the staging docker-compose file, we should add under "web: > volumes:", and "application: > volumes:" the volume mount below:
> 
> ```
> - captchas:/var/www/images/tempcaptcha
> ```
> 
> and under the "volumes:" section at the end of the file, add the following volume:
> 
> ```
> 	captchas:
> ```

@rija I have done the above [here](https://github.com/pli888/gigadb-website/blob/issue-342-captchas/ops/deployment/docker-compose.staging.yml) and you can see the recaptcha image now on the [Contact Us](https://gigadb-staging.gigatools.net/site/contact) page on the staging server. However, you will notice that all the other image files required by the GigaDB website are now missing. This is probably because the images are now not backed into the [`Web-Dockerfile`](https://github.com/pli888/gigadb-website/blob/issue-342-captchas/ops/packaging/Web-Dockerfile) container image as the `COPY images /var/www/images` instruction is not there anymore which is used to build the `production_web` image for staging as defined in [`docker-compose.build.yml`](https://github.com/pli888/gigadb-website/blob/issue-342-captchas/ops/deployment/docker-compose.build.yml).

Maybe we could have a conditional statement in`Web-Dockerfile` that runs the COPY images /var/www/images` line depending if it is a local or staging deployment?

**Comment by rija** [comment]
@pli888 

Well spotted! 
I think we should follow the same approach to folders for the web container service and for application services (i.e: mounted on dev, baked on staging/production).

So it's best to make a ``Production-Web-Dockerfile``  with baked-in images folders and change ``docker-compose.build.yml`` so that the ``web:`` section makes use of that Dockerfile.
Then on staging, **/var/www/images/** is backed from ``docker-compose.build.yml``, and **/var/www/images/tempcaptcha** is overlayed on top with a bind mount  from the ``docker-compose.staging.yml`` file.

**Comment by pli888** [comment]
@rija The **production_app** container is responsible for generating the recaptcha images which gets stored in its `/var/www/images/tempcaptcha`.  Therefore, the contents of this directory needs to be shared with the same folder in the **production_web** container. When this is done using a mounted volume then both the recaptcha and other website images are displayed by the [staging](https://gigadb-staging.gigatools.net/site/contact) GigaDB website.
