### ISSUE TITLE
Which database do the functional tests run against?

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#362]
Before functional tests are executed, the `tests/unit_functional` script prepares a database which provides data for the functional tests to run against:
```
echo "Preparing the database for functional tests..."
exec 3>&1
exec 1> /dev/null
pg_restore -h $GIGADB_HOST -U $GIGADB_USER -d $GIGADB_DB --clean --no-owner -v /var/www/sql/gigadb_testdata.pgdmp || true
exec 1>&3
```

The above code will load the test data from the `gigadb_testdata.pgdmp` file into the same `gigadb` database that the GigaDB dev application uses. However, the functional tests are configured via `protected/tests/phpunit.xml` to test against a GigaDB Yii application started by `bootstrap.php` which will use the `gigadb_test` database that is configured in `db_test.json`.

@rija If the above thinking is correct then I'm not sure if it is the `gigadb` or `gigadb_test` database that the functional tests will run against?

**Comment by rija** [comment]
Hi @pli888,

Functional tests run against main database (gigadb).

The test code execute commands to be executed by a programmatic web browser.

If you look at a functional test, you'll see it inherits from FunctionalTesting.php where the programmatic browser is configured.

Therefore, the http calls hit the running development instance which by default use the main database (gigadb).

phpunit's bootstrap is not used by functional testing.

For functional testing, the phpunit.xml is used only to configure test output and coverage logging.

I agree that it's confusing though and I've refactored it in the Pull Request [#346](https://github.com/gigascience/gigadb-website/pull/346) so that unit tests and functional tests have distinct bootstrap files (because they have different database initialisation requirements) and the phpunit.xml is used for common configuration and suites definition
