### ISSUE TITLE
Viewing/finding files from very large datasets

### ISSUE THREAD

**Issue by ScottBGI** [gigascience/gigadb-website#437]
Feedback from Gane Wong on usability of the 1KP dataset, and how we need to change the way we view files for very large datasets. This example has >7000 files and currently its not very usable to trying to pull out specific files you want. And going forward we are likely to have more and more projects with very large numbers of files.

See the GigaDB entry for the 1KP data:

http://dx.doi.org/10.5524/100627

And for comparison see the corresponding Cyverse dataset:

https://doi.org/10.25739/8m7t-4e85.

Feedback from Gane:
Right now the list is a mess as there 7289 files and even if we show 200/page it is not possible to step to an arbitrary page. You have to step through sequentially. At least on cyverse you can guess which page you need and jump directly to it. Compared to the Cyverse site this also presents a list of a thousand plus files but there are broken into 15 pages and you could jump to any one you want.

The reason GigaDB has over 7000 was they did not group by species. Again that information was provided, right in the file names. Obvious just by looking. In any case the problem is even if you show 200 files/page there are still about 40 pages and the buttons at the bottom only go from 1 to 10 or something like that. You cannot jump ahead to page 35. You have to do it one-by-one. 

Here’s an easy solution. At the bottom of the webpage there are tabs labelled 1 to 10 and a “next” button. The problem is “next” only advances by one webpage, and each “next” takes a few minutes to download. If there are 80 webpages you can imagine the problem. I suggest we simply get rid of the “next” button and generate a tab for EVERY possible page. Default to 100 files/page so the total number of tabs is more reasonable. But don’t make people manually push “next” forever.

Even better idea. Since the list is alphabetic, instead of having to guess which page to go to, let the user enter the first few letters of the file and go to the first page with such files.

**Comment by only1chunts** [comment]
There is a long-standing ticket for improving the file browser (#63 ), I've added this ticket on user feedback there.

**Comment by only1chunts** [comment]
Another example of a dataset with too many files to view properly is www.doi.org/10.5524/100310 , with 19981 files! The webpage actually fails to load most of the time! We may need to bundle and tar.gz some of those.

**Comment by ScottBGI** [comment]
Gane has been chasing up and asking if we could do one of his workaround options first as they'd quite like to issue a correction to the paper but don't want to highlight the data till it's more usable. Any timeline I can give him for a temp or full fix?

**Comment by pli888** [comment]
Another option is to have something like this at the bottom of the dataset webpage:

[<<First]()    [<Prev]()    Page `[ 1 ]` of 385    [Next>]()    [Last>>]()

The `[ 1 ]` is a text box where users can enter a page number that they want to go to.

The tech team will discuss this on Monday.

**Comment by pli888** [comment]
@ScottBGI 

>Another option is to have something like this at the bottom of the dataset webpage:
><<First <Prev Page [ 1 ] of 385 Next> Last>>
>The [ 1 ] is a text box where users can enter a page number that they want to go to.

@kencho51 will start looking into implementing the above functionality.

**Comment by ScottBGI** [comment]
I think this would be a great workaround that will make it a lot more usable. Thanks!

**Comment by pli888** [comment]
@ScottBGI @only1chunts Can you comment on the functionality developed by @kencho51 for viewing datasets with many files: https://gigadb-staging.gigatools.net/dataset/view/id/100704/Files_page/1

**Comment by ScottBGI** [comment]
Looks great to me but I'll check with Gane if it satisfies him. Awesome work @kencho51.

**Comment by only1chunts** [comment]
Hi, Thanks @kencho51 the looks is great and superficially the functionality is good, however there are a couple of issues when i try to do things:
1 - when I try to edit the table settings the selection boxes are tiny dots (instead of tick boxes) that are almost impossible to tell if they are selected or not
![Screenshot_12](https://user-images.githubusercontent.com/6037145/91526996-c3a51500-e8fc-11ea-98d1-9a420bfecd13.png)

2 - The sort by column header doesn't appear to be working properly, e.g. I clicked sort by "Data type" it does appear to sort the files that are currently showing in the table, but when I change page that sorting disappears ...

3 - and I realized that it has only sorted the items showing in that page, not the entire list of files as its meant to.
Thanks
Chris

**Comment by ScottBGI** [comment]
Feedback from Gane (who sounds otherwise happy):

That should work for a few thousand files. the limit is 200 entries per page. i would not bother increasing that. scrolling becomes impossible after that. for larger data sets you'll have to provide other indexing capabilities. or search. but for a few thousand files this should be ok.

**Comment by pli888** [comment]
@only1chunts 

>there are a couple of issues when i try to do things:
1 - when I try to edit the table settings the selection boxes are tiny dots (instead of tick boxes) that are almost impossible to tell if they are selected or not
2 - The sort by column header doesn't appear to be working properly, e.g. I clicked sort by "Data type" it does appear to sort the files that are currently showing in the table, but when I change page that sorting disappears ...
3 - and I realized that it has only sorted the items showing in that page, not the entire list of files as its meant to.

I would like to merge this new pagination feature into the develop branch. The bugs you have identified are reported in issue #505.
