### ISSUE TITLE
504 Gateway Timeout errors on dataset webpages

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#537]
If a dataset has associated publications, then it's webpage might take a long time to load. This is because the web page is waiting for citation information about publications before it is displayed.

For example, a GET request to `http://dx.doi.org/10.1186/2047-217X-1-14` is made by http://gigadb.org/dataset/100039. If this dataset page is loaded on a local deployment using http://gigadb.gigasciencejournal.com:9170/dataset/100039 then it can result in an error message:
```
Server error: `GET http://dx.doi.org/10.1186/2047-217X-1-14` resulted in a `504 Gateway Timeout` response
```

Because of this problem, acceptance tests involving dataset pages such as `@author-names-display` can fail as expectations do not end up being displayed if the page is not loaded in time. For example, see [here](https://gitlab.com/gigascience/forks/kencho51-gigadb-website/-/jobs/890122509).

The GET request to http://dx.doi.org/10.1186/2047-217X-1-14 is made in getPublications() in StoredDatasetConnections class.

Perhaps this can be made as a AJAX call to fix this problem?

**Comment by only1chunts** [comment]
not sure if it helps, but there might also be an option to pull the information directly from the CrossRef API using the DOI details.
https://www.crossref.org/education/retrieve-metadata/
that might reduce the reliance of the DOI resolver AND the GigaScience website both needing to be working

**Comment by rija** [comment]
Hi @pli888

I run into same issue on my branch a while ago.
I thought i fixed it, but I've just tagged the impacted acceptance tests and skip them as it was a distraction from my main work.

Before that, I thought the issue was that we are not using the resolver correctly, because:

*  the DX endpoint is deprecated 
* and we're passing a Request header that seems no longer supported ('style' => 'apa')
* we are not using HTTPS to make the query 

but fixing the above didn't stop the timeout to happen.

We cannot use AJAX on the frontend as that information we're fetching is core data needed by model classes and the DOI resolver is considered a remote data source and therefore its client implemented in the model layer's ``Stored*`` PHP sub-layer.


The correct approach is to insulate that sub-layer from issues in the underlying data source - actually we should do that for all remote web services and database servers we query  -, to prevent "cascading failures"  by installing a [Circuit Breaker](https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern).

It just might be achieved by modifying the ``try...catch()`` block in ``StoredDatasetConnections.php`` to capture the timeout exception and deal with it gracefully. But I suspect it entails a bit more tweaking like digging into finding the right mechanism(s) that was used to throw the error so it can be captured,
but i didn't have the bandwidth to look into that.


@only1chunts

May be. However the problem could happen with that one too or it could be a wider network issue.
 
In general we should assume that any third party (outside our control) services can and will fail eventually and our systems should be able to deal gracefully with that.

**Comment by pli888** [comment]
On updating the endpoint to `doi.org` and using HTTPS in the query, I find the previously affected acceptance tests are passing locally and on CI/CD. I will go ahead and create a pull request to merge these changes as they are required anyway.

**Comment by rija** [comment]
Hi @pli888 

It would be useful to be able to replicate the issue systematically.

maybe we could add something like the following block to the Nginx config file in ``ops/configuration/nginx-conf/sites/dev/gigadb.dev.http.conf``:

```
     location /test_gateway_error { 
         return 504;
     }
``` 

then have a functional test to hit a dataset page and test the page loads without error.

and then temporarily replace the unreliable url with ``gigadb.dev/test_gateway_error`` (first making the url endpoint in php configurable using config params may be a good futureproof move)

This should make the test fails until we make the necessary change to the code that use the url endpoint.

**Comment by pli888** [comment]
@rija thanks for the suggestion which I will implement. It's interesting to note that the production server does not display the citation information for dataset 100039, just the PubMed identifiers probably because of the intermittent timeout error:

| dev 100039  | production 100039 |
| ------------- | ------------- |
| <img width="1151" alt="100039_dev" src="https://user-images.githubusercontent.com/2101491/107497313-5f85bd00-6bcd-11eb-9582-86788fa173e7.png">  | <img width="1152" alt="100039_production" src="https://user-images.githubusercontent.com/2101491/107497446-8e039800-6bcd-11eb-84fb-56d1000a1ba5.png">  |
