### ISSUE TITLE
Merge fuw-cicd branch to develop E566

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#567]
## User Story

>As a developer
>I want the fuw-cicd branch to be reviewed and merged into develop
>So that previously merged work can be released

## Acceptance Criteria

>Given It has been reviewed and it is rebased on develop's HEAD
>When I merge the branch to develop
>Then I can see the functions of FUW and Gitlab pipeline in the develop branch

## Additional Info

That's the branch with gitlab pipeline for automated deployment and file upload wizard worklflows. It's not just a task because it's quite big in encompasses several necessary actictivies like group code review, end to end testing of workflows, documentation updates, rebasing, ...

https://docs.google.com/document/d/1Ns_OkaRn6mXtcDW37JbrSGZzILzFRGPZJQ2oPe2EuSw/edit#heading=h.ad20bdc8hshg

## Product Backlog Item Ready Checklist

* [x] Business value is clearly articulated
* [x] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [x] Dependencies are identified and no external dependencies would block this item from being completed
* [x] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [x] This item is estimated and small enough to comfortably be completed in one sprint
* [x] Acceptance criteria are clear and testable
* [x] Performance criteria, if any, are defined and testable
* [x] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] All automated test suites are passing on continuous Integration pipeline
* [ ] The item has been merged to the develop branch
* [ ] The item is deployed to the staging environment

This Story is part of Epic #566

**Comment by only1chunts** [comment]
There are some workflow anomalies to do with misunderstanding the various roles (my fault for poor documentation, sorry) e.g. generate a reviewer link (~19mins in video) is too late as we need to do that before the MS review process. 

We do not want to input the reviewer's email address in GigaDB to send them the mockup link because (a) curators don't necessarily know who the reviewers are, and (b) there will usually be more than 1 reviewer. The editors are responsible for inviting reviewers and they will need to send the link with their invitation to review the manuscript. Once integrated with RVT the link will be shared in RVT for the Editors to send out, until then we can just copy and paste it into the RVT form (or an email to the editors for GS manuscripts).

The workflow shown in the [miro ](https://miro.com/app/board/o9J_lCDeiKU=/)board maybe useful to help clarify the expected workflow.

Any file attributes that get removed because they are not in the attributes table (or sample table) need to be challenged/reviewed manually so that they can be added if required or adjusted if just a typo. 
I think the file attributes need to be validated before the MS peer-review.

Can we see the content of the automated emails that will be sent out so we can adjust the wording (if required)? particularly for those sent to the submitting author for uploading and updating their files.
