### ISSUE TITLE
Create and run search and replace script on local database

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#629]
Beware,not all ftp links are hosted by us.
But when it is, it's always the same hostname

Exmaple of query we can use:
```
update media_instance set location=replace(location,'v.','')
where location like '%/0/v.%'
```

This task is part of Story #617

**Comment by only1chunts** [comment]
An additional related point that I've just realised....
The DATASET table contains a variable called ftp_site which also holds a link to the FTP site which needs to be updated.
The screenshot shows the location of this link on the public dataset page for your information:
![Screenshot_11](https://user-images.githubusercontent.com/6037145/118836926-3f485700-b8bc-11eb-9f08-6ea529329f41.png)

At some point in the future it maybe more efficient to make that link a website-level thing just using the DOI instead of adding the full FTP path to the database for every dataset!

**Comment by rija** [comment]
Hi @only1chunts 
that ftp_site link is in the code, not in the database. I don't think it's worth our time  and the risk to make that change.
It's more important to get the links to individual dataset files working which is feasible because it's an update to the database content.
Feel free to make a new PBI to describe how that part should be like in the future.

**Comment by only1chunts** [comment]
Hi Rija,
At the moment that link is in the database not the website code. I'm
suggesting it should be in the website code at some point in the future,
but right now the links in the database need to be updated with the cngb
file server location.
The link is stored in the dataset table.
Cheers
Chris

**Comment by rija** [comment]
Hi @only1chunts,

I guess you are referring to the value of the ``ftp_site`` column in the ``file`` table, then?
I''ll update the acceptance scenarios on the main story #617 to reflect that.
Thanks.

**Comment by only1chunts** [comment]
That's correct. Thanks.

**Comment by only1chunts** [comment]
closing as work is completed
