### ISSUE TITLE
dataset 100133

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#680]
We have a "pending" dataset 100133. Its never been published, we have files listed in the database.
- Need to find out why it was never published (was it meant to be?!)
- do we actually have the data files on the server?
- decide if this should be deleted?

**Comment by ChrisArmit** [comment]
Hi Chris,

I cannot find any emails in database@gigasciencejournal.com about this dataset, but I know that the first datasets I worked on were 100362, 100364 and 100365 back in Nov 2017.

Dataset 100133 was quite some time before Mary Ann and I joined Giga. Is it possible you sent emails from your chris@gigasciencejournal.com email account back then?

Cheers
Chris A

**Comment by ChrisArmit** [comment]
Hi @only1chunts ,

Mystery solved! You were awaiting this manuscript to be resubmitted, which is why the dataset was never published (see forwarded message below).

From: Chris Hunter <chris@gigasciencejournal.com>
Subject: Re: BGI-HK servers
Date: 15 August 2016 at 5:12:36 PM HKT
To: Si Zhe Xiao <jesse@gigasciencejournal.com>
Cc: Peter Li <peter@gigasciencejournal.com>

please note that 100133 is hidden, it will require root access to copy that data (its a minion dataset for a manuscript that was expected to be resubmitted, but as yet hasn't been)

**Comment by only1chunts** [comment]
requested deletion of 100133 folder and its contents from Wasabi.
https://github.com/gigascience/dataset-tracking/issues/106
