### ISSUE TITLE
[S617] Run the tool against production database

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#691]

**Comment by pli888** [comment]
This tool ran fine against the production database. However, this task required 9 hours, mostly due to the ~5 hours it took to process dataset_id 629.

Some more recent production datasets had `ftp_site` and `location` starting with `https` already and the tool detected this.

I also used `pg_isready` to check I could connect with the production database, for example to do this with the `pg9_3` database container:
```
$ docker-compose run --rm updater pg_isready -h pg9_3 -U gigadb -d gigadb
Creating files-url-updater_updater_run ... done
pg9_3:5432 - accepting connections
```
