### ISSUE TITLE
handle multiple middle names of authors

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#81]
This should be considered in conjunction with #80 & #82 
 
Many authors have more than 1 middle name. e.g. Thomas Gilbert = M Thomas P Gilbert. or Irene Wing Shan Chik,  Steve Kwan Hok Tong, Kwok Wing Stephen Tsui etc.... we need a method to enable the display of names to be slightly more configurable. Perhaps the easiest method is to have a new column in the database for "display name", which auto populates with the usual first initial of each name, but can be over-written if required (in admin pages) so Steve Kwan Hok Tong - autopopulates to "Tong SK" but can be updated to "Tong SKH" if required. The webpage then takes the display name to generate the web-view.  
The citations are listed in GigaScience papers as . e.g Hebsgaard MB, Gilbert MTP, Arneborg J

**Comment by only1chunts** [comment]
This is the same issue as ticket #8 but this solution is better so I have closed #8.
Some of our authors have multiple middle initials,
e.g. "Teo A S M", is currently stored in the database as:
Surname = "Teo"
middle name = "SM"
first name = "Audrey"
but displays on the dataset as "Teo, A S" (http://gigadb.org/dataset/100165) instead of "Teo A S M".
Make it so that the website displays the 1st letter of each word of middle_name column. We then need to store the names in the database with spaces between multiple middle initials e.g.
Surname = "Teo"
middle name = "S M"
first name = "Audrey"

**Comment by rija** [comment]
Hi,

As the goal of this change request is to allow the accommodation of: the diversity of names,
a standardised format (Gigascience Journal), and ability to tweak the displayed information,
I suggest the implementation of the following display algorhitm:

1. extract surname 
2. extract first letter of every word in first_name and middle_name field 
3. If only capital letters are entered in one of the first_name or middle_name field, return each of the capital letter before moving on to the next word.
4. If a period, space or comma is met, it is considered as a word separator and algorithm will apply to the words before and after
5. merge all initials into one string 
6. return the resulting display name in the order: Surname, initials string, separated by a space

Below, I take a sample of author records from the database and apply the algorithm to each. 


Given the author has surname ``surname``
And the author has first name ``first_name``
And the auhor has middle name ``middle_name``
When gigadb web site shows a paper by the author
Then the author's name should be displayed as ``display_name``

Examples:

| surname | first_name | middle_name | display_name |
|----------|-----------|---------------|--------------|
| Teo | Audrey | SM | Teo ASM |
| Gilbert | M.Thomas | P | Gilbert MTP | 
| Muñoz | Ángel | GG | Muñoz ÁGG | 
| Martinez-Cruzado | Juan | Carlos | Martinez-Cruzado JC |
| Shen | Yong-Yi | | Shen Y | 
| Tong | Steve | KwanHok | Tong SK |
| Tong | Steve | Kwan.Hok | Tong SKH |
| Tong | Steve | Kwan,Hok | Tong SKH |
| Tong | Steve | Kwan Hok | Tong SKH |
| Tong | Kwan Hok | Steve | Tong KHS |


In the last example, the middle name has been entered as "KwanHok" in the database, but if the middle name is changed by the author 
to "Kwan Hok" or "Kwan.Hok" or "Kwan,Hok"
then the resulting display name would be: Tong SKH

It will help to have a **preview area** in the author edit form, so that form user can see in the preview how the name would be displayed on the web site. 

Thus, with this predictable algorithm and a preview area, authors (or admins) have the flexibility to experiment in the form's existing name fields to influence how the name is displayed.

Let me know if the above examples and suggestion meet your goal for this ticket.

**Comment by only1chunts** [comment]
thank you Rija, this is perfect! 
Cheer
Chris

----- Original Message -----

**Comment by rija** [comment]
Hi @only1chunts,

I've made a first implementation of this functionality on my branch:
https://github.com/rija/gigadb-website/tree/author-names-81

You can see the stories and acceptance criteria on the page below (click the [+] all button to expand and see them)

https://rija.github.io/gigadb-website/scenarios_report/author-names-80-81-82.html


It implements the algorithm I've described (see the examples in the page) but it scales down a little the idea of preview area in the form:
The form is so small and simple (only 4 fields matching the database colum of the author table), that it's no less quick and convenient if I add a display name preview field in the author view page the curator sees after updating an author form.
(Maybe adding an "edit" button on the author view for admin users would make that even more easier to make further correction)

Whereas a faithful preview area in the form would require a round-trip with the server for an ajax call, which is not resource efficient.


Other observations I made during my implementation shown in the example on the above acceptance criteria page:

(1) There are some abbrievated names who are meant to stay lowercase. See the example of "Hekkert BtL", the "t" should stay lowercase, as shown in the pubmed article linked from the dataset: https://www.ncbi.nlm.nih.gov/pubmed/21743474
Therefore the algorithm only abbreviate, it won't capitalise. Authors would have to capitalise appropriately for the case to be retained (which is what is happening anyway, looking at sample from the database).

(2) Accentuated characters (issue #82) are now represented correctly as seen in the example "Muñoz ÁGG" and "Schiøtt M"

(3) Some trailing special characters are filtered out automatically as seen in "Schiøtt, "

(4) Some names have a "Jr" attached, this should not be abbreviated hence the resulting display name "Loughran TPJr", the corresponding Gigascience manuscript preserve the "Jr" in the list of references: https://academic.oup.com/gigascience/article/2/1/1/2656134



Let me know what you think.

**Comment by only1chunts** [comment]
I think that all sounds great, I think I need to see it in action to understand if it does what I need so I will ask @jessesiu to get it up and running on his machine for me to see.

**Comment by only1chunts** [comment]
Hi @rija , I've had a look at the version @jessesiu got running on his machine, it appears to be mostly fine but when I look at the admin page of the authors (e.g. http://127.0.0.1:9170/adminAuthor/update/id/3789 ) I have no way to update the display name?

**Comment by rija** [comment]
Hi @only1chunts,

The list of examples in the acceptance test scenarios was to show how the display format of an author’s name can be tweaked  in a variety of ways while adhering to Gigascience Journal’s reference standards.

As it is implemented, there is no explicit editable display name field for you to type in. 
The variety of ways an author’s name could be displayed as can be obtained by using the existing fields (Surname, First name, and Middle name) on the new formatting rules. Additionally, the author’s view screen has a display field to show how it would appear on a dataset page. 

What I understand in your last comment, is that, irrespective of those new rules and how an author name’s elements can be edited in existing fields, there is a need for an additional free-form, editable, display name field on that form.
Could you confirm that my understanding there is correct?

**Comment by only1chunts** [comment]
Hi, yes that is correct. Thanks. 

⁣Sent from Blue ​

**Comment by rija** [comment]
Thank you. 

In that case, two things: 

1. We will need a new varchar column (``custom_name``) in the ``author`` database table
2. We need to add the following two acceptance criteria:
```

Scenario: If custom display name field is empty, save calculated value 
	Given I sign in as an admin
	And I am on "/adminAuthor/update/id/19"
	When I fill in "Author_surname" with "Poe"
	And I fill in "Author_first_name" with "Edgar"
	And I fill in "Author_middle_name" with "Allan"
	And I press "Save"
	Then I should see "Poe EA"


Scenario: when display name edited, save it instead of calculated value
	Given I sign in as an admin
	And I am on "/adminAuthor/update/id/19"
	When I fill in "Author_surname" with "Poe"
	And I fill in "Author_first_name" with "Edgar"
	And I fill in "Author_middle_name" with "Allan"
	And I fill in "Author_custom_name" with "PEA"
	And I press "Save"
	Then I should see "PEA"
```
